### ISSUE TITLE
What is the software license of TxFS?

### ISSUE THREAD

**Issue by ivanagui2** [ut-osa/txfs#2]
For the sake of clarity, what is the software license of TxFS?

**Comment by fcicq** [comment]
the author updated LICENSE file, GPLv2. Note that all the filesystem linked with linux kernel should be licensed under GPLv2 (so ZFS has legal arguments while ZFS-FUSE is ok, as long as FUSE is GPLv2).

**Comment by ivanagui2** [comment]
Just as I was imaginating (some people weren't). Thank you very much for the clarification.

**Comment by yige-hu** [comment]
Ah, yea. Sorry for the late reply. I updated with a LICENSE file.
