### ISSUE TITLE
Code Execution

### ISSUE THREAD

**Issue by jahidhasanlinix** [ut-osa/txfs#3]
How do I use your code to run and do the experiment, can you provide some more instructions.

**Comment by yige-hu** [comment]
You can compile the kernel as usually how linux kernel gets compiled, and either install the kernel or run it in a VM (e.g. QEMU) (more recommended). Then, you can use the systems calls to wrap file system operations, with pairs of txn begin (syscall 322) with txn end (syscall 323) or txn begin with txn abort (syscall 326) system calls. Examples are in the benchmarks directory.
